version: '3.8'
services:
  dolimariadb:
    image: mariadb:10.6
    container_name: dolimariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: AT3eZvcda2frR4F3qGgQLbDV
    logging:
      driver: syslog
    networks:
      - dolibridge
    volumes:
      - /opt/dolidocker/mariadb/data:/var/lib/mysql
      - /opt/dolidocker/mariadb/conf.d:/etc/mysql/conf.d

  dolipma:
    image: phpmyadmin:latest
    container_name: dolipma
    restart: unless-stopped
    ports:
      - 13880:80
    environment:
      - PMA_HOST=dolimariadb
      - PMA_PORT=3306
    networks:
      - dolibridge

  doliphp:
    container_name: doliphp
    build:
      context: .
      dockerfile: dockerfile_php
#    image: php:7-fpm-alpine
    networks:
      - dolibridge
    volumes:
      - /opt/dolidocker/nginx/www/htdocs:/script:ro

  dolinginx:
    image: nginx:stable-alpine
    container_name: dolinginx
    restart: unless-stopped
    depends_on:
      - dolimariadb
      - doliphp
    networks:
      - dolibridge
    volumes:
      - /opt/dolidocker/nginx/www/htdocs:/usr/share/nginx/html
      - /opt/dolidocker/nginx/log:/var/log/nginx
      - /opt/dolidocker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3880:80

networks:
  dolibridge:
    name: dolibridge

