FROM php:7-fpm-alpine
RUN apt install -y libpq-dev
RUN apt install -y zlib1g-dev libzip-dev libpng-dev
RUN apt install -y libfreetype6-dev libjpeg62-turbo-dev libgd-dev
RUN docker-php-ext-configure gd --with-jpeg=/usr/include/ --with-freetype=/usr/include/
RUN docker-php-ext-install gd
RUN docker-php-ext-install zip
