version: '3.8'

secrets:
  mariadb_root_password:
    file: ./secret.mariadb_root_password
  mariadb_db_user:
    file: ./secret.mariadb_db_user
  mariadb_db_user_password:
    file: ./secret.mariadb_db_user_password

services:
  dolimariadb:
    image: mariadb:10.6
    container_name: dolimariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MARIADB_DATABASE: dolibarr
      MARIADB_USER_FILE: /run/secrets/mariadb_db_user
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_db_user_password
    logging:
      driver: syslog
    networks:
      - dolibridge
    volumes:
      - /opt/dolidocker/mariadb/data:/var/lib/mysql
      - /opt/dolidocker/mariadb/conf.d:/etc/mysql/conf.d
    secrets:
      - mariadb_root_password
      - mariadb_db_user
      - mariadb_db_user_password
    profiles:
      - main

  dolipma:
    image: phpmyadmin:latest
    container_name: dolipma
    restart: unless-stopped
    environment:
      - PMA_HOST=dolimariadb
      - PMA_PORT=3306
    networks:
      - dolibridge
      - traefik
    profiles:
      - pma
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dolipma.entrypoints=websecure,web"
      - "traefik.http.routers.dolipma.rule=Host(`pma.dolitest.mproove.net`)"      
      - "traefik.http.routers.dolipma.tls=true"
      - "traefik.http.routers.dolipma.tls.certresolver=lets-encrypt"
      - "traefik.http.services.dolipma.loadbalancer.server.port=80"

  doliphp:
    container_name: doliphp
    user: "33:33"
    build:
      context: .
      dockerfile: dockerfile_php
    networks:
      - dolibridge
    volumes:
      - /opt/dolidocker/nginx/www/htdocs:/script
    profiles:
      - main

  dolinginx:
    image: nginx:stable-alpine
    container_name: dolinginx
    restart: unless-stopped
    depends_on:
      - dolimariadb
      - doliphp
    networks:
      - dolibridge
      - traefik
    volumes:
      - /opt/dolidocker/nginx/www/htdocs:/usr/share/nginx/html
      - /opt/dolidocker/nginx/log:/var/log/nginx
      - /opt/dolidocker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    profiles:
      - main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dolinginx.entrypoints=websecure,web"
      - "traefik.http.routers.dolinginx.rule=Host(`dolitest.mproove.net`)"      
      - "traefik.http.routers.dolinginx.tls=true"
      - "traefik.http.routers.dolinginx.tls.certresolver=lets-encrypt"
      - "traefik.http.services.dolinginx.loadbalancer.server.port=80"

networks:
  dolibridge:
    name: dolibridge
  traefik:
    name: traefik
    external: true

